version: "3.7"

networks:
  web:
   external: true
  vbr:

# NOTE: Traefik must be ran on `web`

services:
  vbr:
    image: ghcr.io/nathan13888/vbr:latest
    #build: .
    restart: unless-stopped
    container_name: vbr
    environment:
      - "DEBUG=enabled"
      - "KEY=guess_what"
      - "REDIS_URL=redis://:@redis:6379/0" # TODO: using TiKV in the future
      - "SHIELDS_URL=http://shields:9090" # don't have a trailing slash
      - "MAINTENANCE=enabled" # options: enabled, <anything else>
    ports:
      - "127.0.0.1:8080:8080"
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.vbr-router.tls.certResolver=lets-encrypt"
      - "traefik.http.routers.vbr-router.rule=Host(`vbr.wocr.tk`)"
      - "traefik.http.routers.vbr-router.service=vbr"
      - "traefik.http.services.vbr.loadbalancer.server.port=8080"
    networks:
      - web
      - vbr
    depends_on:
      - redis
      - shields

  shields:
    image: shieldsio/shields:server-2021-05-01
    restart: unless-stopped
    container_name: shields
    environment:
      - "NODE_ENV=production"
      - "PORT=9090"
    # ports:
    #   - "127.0.0.1:9090:9090"
    expose:
      - 9090
    networks:
      - vbr

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    # name: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - 6379
    volumes:
      - ./data:/data
      - ./redis_conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - vbr

