version: "3.7"

networks:
  web:
   external: true
  vbr:

# NOTE: Traefik must be ran on `web`

services:
  vbr:
    #image: docker.pkg.github.com/nathan13888/visitorbadgereloaded/vbr:latest
    build: .
    restart: unless-stopped
    container_name: vbr
    environment:
      - "DEBUG=enabled"
      - "KEY=guess_what"
      # - "REDIS_URL=redis://vbr:vbr_verysecurepassword1234yes@redis:6379/0" # TODO: EDIT
      - "REDIS_URL=redis://:@redis:6379/0"
    ports:
      - "127.0.0.1:8080:8080"
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.vbr-router.tls.certResolver=lets-encrypt"
      - "traefik.http.routers.vbr-router.rule=Host(`vbr.wocr.tk`)"
      - "traefik.http.routers.vbr-router.service=vbr"
      - "traefik.http.services.vbr.loadbalancer.server.port=8080"
    networks:
      - web
      - vbr
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    # name: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - 6379
    volumes:
      - ./data:/data
      - ./redis_conf/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - vbr

