#:schema node_modules/wrangler/config-schema.json
name = "vbr"
main = "src/index.ts"
compatibility_date = "2024-11-20"

compatibility_flags = ["nodejs_compat"]
send_metrics = false
workers_dev = false
preview_urls = false

routes = [
    { pattern = "vbr.nathanchung.dev", zone_name = "nathanchung.dev", custom_domain = true },
]

[limits]
cpu_ms = 30

[observability]
enabled = true
logs.enabled = true
head_sampling_rate = 1

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "vbr_badge_counts"
id = "6a63980cfdb6493ca4bb8e8817060543"

# TODO: cron backup job

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
